# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
